"""initial schema: extensions, all tables, append-only triggers, ivfflat

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-13

Hand-written (not autogenerated) because the baseline needs ordered steps that
autogenerate cannot emit: CREATE EXTENSION, the audit sequence, the ivfflat
index, and the append-only reject triggers. Tables themselves are created from
the ORM metadata so the migration can never drift from models.py.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

from opsforge.models import Base

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# One shared reject function + BEFORE triggers make audit_log and run_events
# truly append-only (UPDATE/DELETE/TRUNCATE all rejected at the DB).
_REJECT_FN = """
CREATE OR REPLACE FUNCTION reject_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'Table % is append-only: % is not allowed', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'integrity_constraint_violation';
END;
$$ LANGUAGE plpgsql;
"""

_APPEND_ONLY_TABLES = ("audit_log", "run_events")


def _row_trigger(table: str) -> str:
    return (
        f"CREATE TRIGGER trg_{table}_append_only_row "
        f"BEFORE UPDATE OR DELETE ON {table} "
        f"FOR EACH ROW EXECUTE FUNCTION reject_mutation();"
    )


def _truncate_trigger(table: str) -> str:
    return (
        f"CREATE TRIGGER trg_{table}_append_only_trunc "
        f"BEFORE TRUNCATE ON {table} "
        f"FOR EACH STATEMENT EXECUTE FUNCTION reject_mutation();"
    )


def upgrade() -> None:
    conn = op.get_bind()

    # 1. Extensions: pgcrypto -> gen_random_uuid(); vector -> pgvector type/index.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")

    # 2. Monotonic sequences referenced by table defaults in the ORM metadata. create_all
    #    builds the CURRENT models.py, so every *_seq a server_default uses must exist
    #    before it runs (the later milestone migrations also create these IF NOT EXISTS;
    #    declaring them here makes a from-scratch migration valid).
    for seq in ("audit_log_seq", "findings_seq", "process_dispositions_seq",
                "validated_processes_seq"):
        op.execute(f"CREATE SEQUENCE IF NOT EXISTS {seq};")

    # 3. All tables, indexes, checks, and unique constraints — straight from the
    #    ORM metadata so this baseline matches models.py exactly.
    Base.metadata.create_all(bind=conn)

    # 4. Vector similarity index (not expressible in ORM metadata).
    op.execute(
        "CREATE INDEX ix_patterns_embedding ON patterns "
        "USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);"
    )

    # 5. Append-only enforcement.
    op.execute(_REJECT_FN)
    for table in _APPEND_ONLY_TABLES:
        op.execute(_row_trigger(table))
        op.execute(_truncate_trigger(table))


def downgrade() -> None:
    conn = op.get_bind()

    for table in _APPEND_ONLY_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_append_only_row ON {table};")
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_append_only_trunc ON {table};")
    op.execute("DROP FUNCTION IF EXISTS reject_mutation();")
    op.execute("DROP INDEX IF EXISTS ix_patterns_embedding;")

    Base.metadata.drop_all(bind=conn)

    op.execute("DROP SEQUENCE IF EXISTS audit_log_seq;")
    op.execute("DROP EXTENSION IF EXISTS vector;")
    op.execute("DROP EXTENSION IF EXISTS pgcrypto;")
